### ISSUE TITLE
Slade3 crashes on Linux when opening any graphics file

### ISSUE THREAD

**Issue by Kzer-Za** [sirjuddington/SLADE#1027]
**SLADE Version**: (3.1.4.1)
**Operating System**: (Linux)

**Issue Details**:
The subject. At least it crashes with any of the files that I have. The output of the console is:

```
(slade:24080): Gdk-ERROR **: 19:42:10.592: The program 'slade' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 60185 error_code 2 request_code 154 (GLX) minor_code 24)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
zsh: trace trap (core dumped)  slade
```

The version of X Org server is 1.20.2-1.0
Kernel is 4.19.8-1
Video drivers are NVidia 340.107-7

**Comment by sirjuddington** [comment]
Are you using Wayland instead of X? I had a similar issue with Wayland (apparently wx3.0 opengl canvas doesn't like it, I think it's fixed in wx3.1)

**Comment by Kzer-Za** [comment]
>Are you using Wayland instead of X?

No, I'm using X.

BTW, I updated Slade to 3.1.4.2 and now it gives a different error (it still doesn't open any graphics file):

```
(slade:9343): Gdk-ERROR **: 09:34:32.965: The program 'slade' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 91878 error_code 170 request_code 154 (GLX) minor_code 6)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
zsh: trace trap (core dumped)  slade
```

**Comment by sirjuddington** [comment]
I have no idea what it could be then unfortunately

**Comment by WilliamWBerrutti** [comment]
Hello, I have the same issue. Details below:

```
(slade:8802): Gdk-ERROR **: 11:10:07.577: The program 'slade' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 13128 error_code 170 request_code 154 (GLX) minor_code 6)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```

Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.4
KDE Frameworks Version: 5.64.0
Qt Version: 5.13.2
Kernel Version: 4.19.88-1-MANJARO
OS Type: 64-bit

**Comment by sirjuddington** [comment]
I'm closing all crash issues from before 3.3.0 as there will be no further 3.2.X releases. If the crash still happens in 3.3.0 beta 1 feel free to reopen the issue with an updated stack trace if possible.
