### ISSUE TITLE
Unable to interact in any way with Map Editor on Mac OSX Mojave

### ISSUE THREAD

**Issue by MyrddinEmrys08** [sirjuddington/SLADE#1049]
**SLADE Version**: (3.1.3)
**Operating System**: (OSX)

**Issue Details**:
Slade has historically worked well for me on this computer. I have also deleted the file and then re-downloaded multiple times without issue. However, I recently downloaded the latest version for Mac, and when I tried to open the application via control-click, I got this message:

![Screen Shot 2019-06-01 at 8 31 49 PM](https://user-images.githubusercontent.com/51279962/58756410-02a3ab00-84ad-11e9-8b8a-cb03b918b6e5.png)

I looked up this issue, which seemed to be related to permissions, and used "sudo xattr -rd com.apple.quarantine /Applications/SLADE.app" as suggested by a thread I found and I was able to open Slade without warnings at that point. However, when it did open, the options relating to creating/opening maps were greyed out and could not be clicked:

![Screen Shot 2019-06-01 at 8 34 57 PM](https://user-images.githubusercontent.com/51279962/58756411-02a3ab00-84ad-11e9-98d7-c0b5d1acee52.png)

Additionally, when I opened an old map, I would be unable to interact with the map editor, and it would soon blank out completely, leaving a see-through window: 

![Screen Shot 2019-06-01 at 8 20 14 PM](https://user-images.githubusercontent.com/51279962/58756409-02a3ab00-84ad-11e9-8cfc-320e95095ec0.png)

![Screen Shot 2019-06-01 at 8 20 01 PM](https://user-images.githubusercontent.com/51279962/58756408-020b1480-84ad-11e9-83c4-37eedb914b1e.png)

I've never had a similar issue before with any application, and I'm really not sure what could be going on. It appears that I am still able to edit WAD archives and files, I just can't interact with maps at all (and unfortunately, I use Slade mainly for maps). Any tips/suggestions would be appreciated. Thanks!

"About This Mac" information for my computer, if it is relevant:
![Screen Shot 2019-06-01 at 8 36 33 PM](https://user-images.githubusercontent.com/51279962/58756412-02a3ab00-84ad-11e9-9fa3-150920aece2a.png)

**Comment by sirjuddington** [comment]
This is an issue with wxWidgets 3.1.1 and mojave which has since been fixed in wx, but I'm currently unable to get the mac builds to work unfortunately.

My macbook pro has some kind of hardware issue which causes macos and windows to lock up completely when launched (linux still works fine for some reason), and I don't currently have the money to get it fixed (it's well out of warranty).

Even before it died I was unable to get the builds to work though, so for now the only real option is for someone else to make a build of 3.1.5 (see https://github.com/alexey-lysiuk/slade-macos-build) or try to compile it yourself from source, using homebrew to install the required libraries.

**Comment by sirjuddington** [comment]
Does this still happen in 3.1.6 on mac?

**Comment by MyrddinEmrys08** [comment]
Yes, I tried the download link for 3.1.6 as of today (March 25, 2020) and it has the same issue. It does not give me the message to move it to trash, but I still cannot access the map editor in any way. Meanwhile, all previous versions give the "move to trash" message, and thus Slade effectively doesn't work for me on Mac. 

I understand that issues such as these can arise easily and are hard to resolve; thank you for supporting Mac in the first place. Thank you as well for the feedback, and good luck with trying to fix it if you get the chance.

**Comment by starlit-void** [comment]
hi all, i'm able to compile for macOS (signing fails but it does build the actual .app file).
where is the actual `wxWidgets` dependency version specified?

**Comment by starlit-void** [comment]
i did it, i managed to upgrade to wxWidgets 3.1.3 and build SLADE.

accomplishing this was very messy. in order to push these changes back to you i would need to figure out how to get `find_package` to work from the local "environment" in the slade-macos-build repo.

![image](https://user-images.githubusercontent.com/5959031/85210520-1be1f880-b349-11ea-9892-7c8ce3840d0c.png)

![image](https://user-images.githubusercontent.com/5959031/85210723-1ab1cb00-b34b-11ea-8936-498862bfe402.png)


clearly the colors are better but there are still some issues.
for one, the size of the screen renders wrong. that could be due to retina screen rendering at 2x the resolution. however, the mouse coordinates are taken from the actual window positions - so it is very hard to click on things. i also noticed a lot of artifacts in the 3d mode view. but it is a start!!

**Comment by starlit-void** [comment]
would love to get some pointers on how to proceed here.
can i build a version for others to download? is there a key to sign with? can i push my changes back to you? etc. etc....

**Comment by sirjuddington** [comment]
You can try building it for others to download, though I'm not sure it'd work.

There is no key to sign with, I'm not sure why it's suddenly needed - was never a problem before. If apple have changed it so a key is required then I'm not sure what to do with it, I'm certainly not paying for one just to be able to distribute a free, open source application.

You can push changes back yes, unless the changes are to slade-macos-build in which case it's up to @alexey-lysiuk

**Comment by starlit-void** [comment]
yeah apple wants dmg files & apps to be signed, looks like it costs $100 for a 5-year certificate 🙃 
i wonder if there's a way to package the source code for local building, via homebrew for instance .... then it is less of an issue. i will check on slade-macos-build with @alexey-lysiuk! thank you.
