### ISSUE TITLE
SLADE cannot delete folders in opened directories anymore.

### ISSUE THREAD

**Issue by inkoalawetrust** [sirjuddington/SLADE#1331]
**SLADE Version**: (3.2.0) Beta 4
**Operating System**: (Windows 10 21H2)

**Issue Details**:
As of 3.2.0 Beta 4, SLADE can no longer fully delete subfolders in opened directions. Deleting folders will delete their contents, but won't delete the actual folders, so every time you refocus back to SLADE, you have the Directory Content Changed window appear, telling you that the deleted folders were re-added. Even if you don't add them back in through SLADE, and save your changes again. You will still not have the folders deleted. The only way to get rid of folders entirely anymore. Is by deleting them manually outside of SLADE.

I've attached a link to a video of the bug and me replicating it below, it should be really easy to reproduce. Since all you need to do is try and delete a subfolder from an opened directory.

https://streamable.com/28cn5j

**Comment by sirjuddington** [comment]
Hmm I can't reproduce this one, do you get any errors in the console when you try to save and this happens?

**Comment by inkoalawetrust** [comment]
Well, deleting the folders then trying to save gives me access denied errors in the console for all of them.

```
Error: Directory 'C:\Users\inkoalawetrust\Desktop\test\Taunts\Wave 2' couldn't be deleted (error 5: Access is denied.)
Error: Directory 'C:\Users\inkoalawetrust\Desktop\test\Taunts\Wave 1' couldn't be deleted (error 5: Access is denied.)
Error: Directory 'C:\Users\inkoalawetrust\Desktop\test\Taunts' couldn't be deleted (error 5: Access is denied.)
Error: Directory 'C:\Users\inkoalawetrust\Desktop\test\Rocket Launcher' couldn't be deleted (error 5: Access is denied.)
```

**Comment by sirjuddington** [comment]
Figured, Windows has some weird permission issues, especially to do with the users folder. I'm not sure there is much I can do about that, though it should probably pop up those errors if they happen on save.

**Comment by inkoalawetrust** [comment]
> Figured, Windows has some weird permission issues, especially to do with the users folder. I'm not sure there is much I can do about that, though it should probably pop up those errors if they happen on save.

Are you sure that's the problem ? I've literally never had SLADE have such an issue before, when modifying folders or files in my users folder, and especially not my desktop. Deleting folders from my desktop with SLADE was not even a problem since I updated from 3.1.12.

**Comment by sirjuddington** [comment]
Hmm, I'm not sure then, I know when I've seen access issues like that in the past it's always been in the users folder for whatever reason. Maybe it was in use somehow? Either way can you see if it's fixed in 3.2.0 final? I changed the way folders are deleted so it might work there. If not, there still isn't really much I can do about it (3.2.0 will now at least pop up a dialog with any issues encountered when saving a directory)

**Comment by inkoalawetrust** [comment]
Doesn't seem to be fixed, the folders are still not deleted when you save the changes in SLADE. The only difference is that the console doesn't print out any Access denied errors anymore.
