### ISSUE TITLE
TEXTUREx editor multiple issues both on Linux and Windows

### ISSUE THREAD

**Issue by jmfergeau** [sirjuddington/SLADE#1672]
### SLADE Version

3.2.5, 3.2.6

### OS

Windows, Linux

### Editor

Resource editor

### Steps to Reproduce and Observed Behavior

1. Open a wad or a folder
2. Double-click on a texture lump
3. On Linux, Two things might happen. Slade might just abruptly crash and close with no errors. Or if it didn't crash, the editor will work as intended but the graphical part where you can drag the elements to set the offset will not display anything. It will just display what was behind it before (or just a pitch black window) and will not be usable at all. On Windows, it doesn't crash, but the graphical part is not usable either, displaying this time a pitch red window instead.

### Expected Behavior
the Texturex editor should display the window editor correctly and be fully interactive

NOTE: For the crash on linux, I found a workaround. Very weird, but it works:
1. Open slade and open a wad or folder
2. Open a map with the map editor
4. Grab a linedef and attempt to click the special menu to change it
5. An error dialog will appear. Uncheck the "show dialog next time" and click continue
6. Cancel the special change and close the map editor
7. Double-click the TEXTURE lump. No more crash.

Sorry if it has already been posted. I checked everywhere but haven't found anything similar.

### Screenshots

![The inoperant window on Windows 11](https://github.com/sirjuddington/SLADE/assets/6705075/8d1abbcf-2845-400c-983c-903f894c3d6e)

![The inoperant window on Linux](https://github.com/sirjuddington/SLADE/assets/6705075/c7ab9e01-2c31-4e16-98c7-1536d529bb21)

**Comment by jmfergeau** [comment]
Some additional notes:

I noticed the zoom in and out are somehow working since it can be done using the mousewheel. But nothing displays. I suspect the checkboxes are doing the same.

The fields around the graphic interface are all working and saving the changes works. But it's very difficult to do anything when you can't see what you're doing.

**Comment by UnBeatWaterGH** [comment]
Here's a slightly similar issue I made in July last year: #1549

**Comment by kinker31** [comment]
I'm having the same issue on Linux, where the program instantly crashes, without even so much as a "This program crashed!" dialog box. Luckily, I was able to get it running on my terminal, and when I reproduced the bug, this is what it gave me:
```01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it
01:46:01: Debug: window wxControl@0x564cfb4dec90 ("stbutton") lost focus even though it didn't have it

(slade:50390): Gdk-WARNING **: 01:46:01.931: The program 'slade' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 28145 error_code 3 request_code 148 (unknown) minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I was not able to get anything else from the terminal whilst I was running the program.

**Comment by MyThoughtsAreTurquoise** [comment]
Same issues here. Everything else works just fine, but whenever i open a TEXTURES lump i get one of two things: texture
preview window is black or a crash. luckely i get a application crash notification:

Version: 3.2.5
No current action

Operating System: Linux 5.15.0-105-generic x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:

Last Log Messages:
Loading game configurations
SLADE Initialisation OK
Can't convert "-" to an integer (invalid)
Can't convert "\" to an integer (invalid)
Can't convert "[" to an integer (invalid)
Can't convert "[" to an integer (invalid)
Opening archive /home/odysseus/modBench/Doom/export/mods/qcWeapons/004/qcWeapons4
Opening took 86 ms
Setting up the OpenGL context
Failed to setup the OpenGL context

On my end the crash only happens when i close the program and then try to open the TEXTURES lump for the second time. Whenever i create one, add textures to it and open it up for the first time, the program doesn't crash but then again no preview, just the UI Elements and a black preview window.

![Screenshot at 2024-05-03 16-15-57](https://github.com/sirjuddington/SLADE/assets/137090899/97b80eb5-3ebc-4378-a23f-717af9133903)

I'm using the flatpak version, platforms etc... are all up to date.

Some info about my OS:

System:
  Kernel: 5.15.0-105-generic x86_64 bits: 64 compiler: gcc v: 11.4.0
    Desktop: Openbox 3.6.1 dm: LightDM Distro: Linux Mint 21 Vanessa
    base: Ubuntu 22.04 jammy

Graphics:
  Device-1: NVIDIA GM200 [GeForce GTX 980 Ti] vendor: Micro-Star MSI
    driver: nvidia v: 535.171.04 pcie: speed: 2.5 GT/s lanes: 2 ports:
    active: none off: HDMI-A-1 empty: DP-1, DP-2, DP-3, DVI-I-1
    bus-ID: 01:00.0 chip-ID: 10de:17c8
  Display: x11 server: X.Org v: 1.21.1.4 compositor: Compton v: 1 driver:
    X: loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 92
  Monitor-1: HDMI-0 res: 1920x1080 dpi: 92 diag: 609mm (24")
  OpenGL: renderer: NVIDIA GeForce GTX 980 Ti/PCIe/SSE2
    v: 4.6.0 NVIDIA 535.171.04 direct render: Yes

**Comment by jmfergeau** [comment]
Updated to 3.2.6 and there's some new. Now, when opening a TEXTURE file, the following crash log is reported, similar to #1685 :

```
Version: 3.2.6
No current action

Operating System: Linux 6.9.2-zen1-1-zen x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:
0: [unknown location] [unknown:127534448105524]
1: [unknown location] [unknown:127534350915172]
2: [unknown location] [unknown:127534421576416]
3: [unknown location] [unknown:96352725713355]
4: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
5: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
6: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
7: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
8: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
9: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
10: [unknown location] wxWindow::GTKSendPaintEvents(_cairo*)
11: [unknown location] [unknown:127534468043246]
12: [unknown location] [unknown:127534436419541]
13: [unknown location] [unknown:127534439301320]
14: [unknown location] g_closure_invoke
15: [unknown location] [unknown:127534428474597]
16: [unknown location] [unknown:127534428409408]
17: [unknown location] g_signal_emit_valist
18: [unknown location] g_signal_emit
19: [unknown location] [unknown:127534439367106]
20: [unknown location] [unknown:127534439425475]
21: [unknown location] gtk_main_do_event
22: [unknown location] [unknown:127534435120071]
23: [unknown location] [unknown:127534435196354]
24: [unknown location] [unknown:127534435196215]
25: [unknown location] [unknown:127534435196215]
26: [unknown location] [unknown:127534435196215]
27: [unknown location] [unknown:127534435196215]
28: [unknown location] [unknown:127534435196215]
29: [unknown location] [unknown:127534435196215]
30: [unknown location] [unknown:127534435214815]
31: [unknown location] [unknown:127534435215354]
32: [unknown location] wxWindow::Update()
33: [unknown location] [unknown:127534468464323]
34: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
35: [unknown location] wxSizer::Layout()
36: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
37: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
38: [unknown location] wxSizer::Layout()
39: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
40: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
41: [unknown location] wxSizer::Layout()
42: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
43: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
44: [unknown location] wxSizer::Layout()
45: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
46: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
47: [unknown location] wxSizer::Layout()
48: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
49: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
50: [unknown location] wxSizer::Layout()
51: [unknown location] wxWindowBase::Layout()
52: [unknown location] wxAuiManager::DoFrameLayout()
53: [unknown location] wxAuiManager::OnSize(wxSizeEvent&)
54: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
55: [unknown location] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
56: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
57: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
58: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
59: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
60: [unknown location] wxWindow::DoSetSize(int, int, int, int, int)
61: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
62: [unknown location] wxSizer::Layout()
63: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
64: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
65: [unknown location] wxSizer::Layout()
66: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
67: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
68: [unknown location] wxSizer::Layout()
69: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
70: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
71: [unknown location] wxSizer::Layout()
72: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
73: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
74: [unknown location] wxSizer::Layout()
75: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
76: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
77: [unknown location] wxSizer::Layout()
78: [unknown location] wxWindowBase::Layout()
79: [unknown location] wxAuiManager::DoFrameLayout()
80: [unknown location] wxAuiManager::OnSize(wxSizeEvent&)
81: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
82: [unknown location] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
83: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
84: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
85: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
86: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
87: [unknown location] wxWindowBase::SendSizeEvent(int)
88: [unknown location] [unknown:127534456292807]
89: [unknown location] g_closure_invoke
90: [unknown location] [unknown:127534428475471]
91: [unknown location] [unknown:127534428411356]
92: [unknown location] g_signal_emit_valist
93: [unknown location] g_signal_emit
94: [unknown location] [unknown:127534435176157]
95: [unknown location] [unknown:127534435093104]
96: [unknown location] [unknown:127534428978906]
97: [unknown location] [unknown:127534428973705]
98: [unknown location] [unknown:127534429374903]
99: [unknown location] g_main_loop_run
100: [unknown location] gtk_main
101: [unknown location] wxGUIEventLoop::DoRun()
102: [unknown location] wxEventLoopBase::Run()
103: [unknown location] wxAppConsoleBase::MainLoop()
104: [unknown location] wxEntry(int&, wchar_t**)
105: [unknown location] main
106: [unknown location] [unknown:127534421482632]
107: [unknown location] __libc_start_main
108: [unknown location] [unknown:96352721100549]

Last Log Messages:
Loading game configurations
SLADE Initialisation OK
Can't convert "-" to an integer (invalid)
Can't convert "\" to an integer (invalid)
Can't convert "[" to an integer (invalid)
Can't convert "[" to an integer (invalid)
Opening directory /home/max/Documents/yumedoom as archive
Opening took 9833 ms
Setting up the OpenGL context
Failed to setup the OpenGL context
```

It seems to not find openGL. Though it's installed. (i use mesa drivers)

(Also the problem with the Start page not loading is still there)

**Comment by sirjuddington** [comment]
What version of wxWidgets is it built with? Should say in the console log. I think there might be some issue with the version of wx that the flatpak SLADE is built with

**Comment by jmfergeau** [comment]
I don't use flatpak. I build slade using AUR. Here in this case I compiled slade manually since AUR is not up-to-date yet.

I use wxwidgets v3.2.5

**Comment by jmfergeau** [comment]
I switched to debian for multiple reasons but still same problem in there. I use the flatpak version. (and the crash handler also crashes :| )

**Comment by jmfergeau** [comment]
I switched from flatpak to the debian package available in the drd repos. And all the problems i mentionned got fixed. Start page works again and no issues at all when editing TEXTUREx.

So, tempoprary fix: use Debian and install Slade using the debian drd repo. :man_shrugging:

**Comment by Blzut3** [comment]
Compatibility with all currently supported versions of Debian and Ubuntu.  That said the latest package should have binaries for both (it would be possible to make a single universal binary but I don't really feel like going that deep into dependency building).  Which is used is determined by /usr/bin/slade by running:
```bash
ldconfig -N -p | awk '$1 == "libwebkit2gtk-4.1.so.0"'
```
Does this return nothing for you?

**Comment by jmfergeau** [comment]
> ```shell
> ldconfig -N -p | awk '$1 == "libwebkit2gtk-4.1.so.0"'
> ```
> 
> Does this return nothing for you?

It returns me this:
```
        libwebkit2gtk-4.1.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so.0
```

Debian does weird things tho. ldconfig wasn't even in the path for some reason so i had to do `/sbin/ldconfig` to make it work. 🤷‍♂️

**Comment by Blzut3** [comment]
That's the expected output, so it should be running the 4.1 binary.

**Comment by jmfergeau** [comment]
And yet, if i launch slade without libwebkit2gtk-4.0, i get this and it doesn't run:
```
/usr/bin/slade: 4: ldconfig: not found
/usr/share/slade/slade.legacy: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
```

**Comment by Blzut3** [comment]
You edited out your note about ldconfig needing to specifically be /sbin/ldconfig.  Did you have new information or what that still valid?

I can change the script to specifically call /sbin/ldconfig in the next build, but Ubuntu definitely puts /sbin in the PATH by default.  A bit surprised Debian would differ there.  You can modify /usr/bin/slade accordingly in the mean time, apt should unconditionally overwrite the file on package upgrade.

**Comment by jmfergeau** [comment]
Ubuntu might do that but pure Debian definitely doesn't add `sbin` in `$PATH` for non-root users by default since version 10. Because they expect all the programs in there to be able to run as root only. (Except it's not true. For instance you can do `mkfs.msdos` to make a floppy image file without the need to be root) But well, Debian is Debian. :man_shrugging: 

So yeah maybe it would be relevant to add `/sbin/` in next build, just in case other pure Debian or pure Debian-based users uses Slade (I can't be the only one on the whole planet, eh? :p )

**Comment by SkullGamer205** [comment]
uname -a
```
Linux SkullGamer205-PC 6.9.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000 x86_64 GNU/Linux
```

On X11 (AwesomeWM): Slade crashes after open TEXTUREx editor
On Wayland (Weston): Works, but with black screen. _See below_
![photo_2024-07-31_20-59-52](https://github.com/user-attachments/assets/79faea5a-3125-496f-af6e-87ebece61b24)

![photo_2024-07-31_20-59-57](https://github.com/user-attachments/assets/bf6b2d44-e2f4-4fbb-9264-8bd09fa24045)

**Comment by SkullGamer205** [comment]
> uname -a
> 
> ```
> Linux SkullGamer205-PC 6.9.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000 x86_64 GNU/Linux
> ```
> 
> `wxWidgets ver: 3.2.5-1` `Slade ver: 3.2.6-2`
> 
> On X11 (AwesomeWM): Slade crashes after open TEXTUREx editor On Wayland (Weston): Works, but with black screen. _See below_ ![photo_2024-07-31_20-59-52](https://private-user-images.githubusercontent.com/61167080/353805103-79faea5a-3125-496f-af6e-87ebece61b24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjQxMDQsIm5iZiI6MTcyMjQyMzgwNCwicGF0aCI6Ii82MTE2NzA4MC8zNTM4MDUxMDMtNzlmYWVhNWEtMzEyNS00OTZmLWFmNmUtODdlYmVjZTYxYjI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExMDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNDZjNGJjMzI0MGJkN2I3YTIyMDY1NTU1NGY3ZWIxNDViYTBiODY1OTQwMmU2MmY4MzIzYmQyN2MzNjZlMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eiCwcEPhhAMN72cotKANGJ7g8wimbKkOcpdyMCtFxBE)
> 
> ![photo_2024-07-31_20-59-57](https://private-user-images.githubusercontent.com/61167080/353805088-bf6b2d44-e2f4-4fbb-9264-8bd09fa24045.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjQxMDQsIm5iZiI6MTcyMjQyMzgwNCwicGF0aCI6Ii82MTE2NzA4MC8zNTM4MDUwODgtYmY2YjJkNDQtZTJmNC00ZmJiLTkyNjQtOGJkMDlmYTI0MDQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExMDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZjY4ODIzZjJmZTZkMmEyOGRhMDgyZWVhNWI5OTM2ZjI3YjVhMTY4MzAxNWU2Yzg4ZDEyZGZhNGZkZDNlN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gcqfrv1kaKz3bpWCAx9_3JgykxVhylYaxl5DWJI5im8)

Black screen also show on X11 with nvidia (i.e `prime slade`), but after several seconds Slade crashed.
![изображение](https://github.com/user-attachments/assets/21f9aa78-5ed3-45a5-9883-3ea3a096f134)

**Comment by jmfergeau** [comment]
Heads up to say I had to ditch debian cuz issues and had to return to arch. And i'm still facing the problem :(

**Comment by kinker31** [comment]
Although I'm still having the issue on the native Linux excecutable, I don't experience this problem when I'm running the Windows .exe on Wine. I'd love to get the stack trace, but the program crashes before the window even shows up, and trying to run the program with a terminal only gives a "button lost focus even though it didn't have it" debug message.

If it helps, I use the linux-zen kernel on Arch Linux, with AMD architecture.

**Comment by nkalkhof** [comment]
> > Although I'm still having the issue on the native Linux excecutable, I don't experience this problem when I'm running the Windows .exe on Wine. I'd love to get the stack trace, but the program crashes before the window even shows up, and trying to run the program with a terminal only gives a "button lost focus even though it didn't have it" debug message.
> > If it helps, I use the linux-zen kernel on Arch Linux, with AMD architecture.
> 
> That's the thing. I, like all the others who got the problem, use nvidia.

I don't think it is GPU(driver) related because I'm having the same issues on Gentoo Linux running an Intel UHD630 GT2 iGPU. I Successfully build the latest git master using the cmake flag to pull and build it's own wxWidgets. Still the same crash. No idea why @sirjuddington won't try fix that. Maybe he cannot reproduce it?!

**Comment by Blzut3** [comment]
Well jmfergeau noted that it doesn't happen on Debian with my packages.  I can't say I'm doing anything particularly special with my packages besides building wxWidgets and SFML myself for static linking.  My binaries are built with GCC 11.

wxWidgets build:
```
cmake .. -DwxBUILD_TOOLKIT=gtk3 -DCMAKE_BUILD_TYPE=Release -DwxBUILD_SHARED=OFF -DwxUSE_LIBTIFF=builtin -DwxUSE_LIBLZMA=sys -DwxUSE_LIBPNG=builtin -DCMAKE_INSTALL_PREFIX=$UsrPrefix -DwxUSE_LIBJPEG=builtin -DwxUSE_WEBVIEW=ON -DwxUSE_REGEX=builtin -DwxUSE_GLCANVAS_EGL=OFF=OFF
```

Slade build:
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DWITH_WXPATH=$UsrPrefix -DSFML_CONFIG=$UsrPrefix/lib/cmake/SFML/SFMLConfig.cmake -DSFML_STATIC_LIBRARIES=TRUE -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON -DSFML_LIBRARY="sfml-system;sfml-audio;sfml-network;sfml-window" -DFLUIDSYNTH_LIBRARIES=fluidsynth
```

Nothing special about the SFML build.

**Comment by nkalkhof** [comment]
> cmake .. -DwxBUILD_TOOLKIT=gtk3 -DCMAKE_BUILD_TYPE=Release -DwxBUILD_SHARED=OFF -DwxUSE_LIBTIFF=builtin -DwxUSE_LIBLZMA=sys -DwxUSE_LIBPNG=builtin -DCMAKE_INSTALL_PREFIX=$UsrPrefix -DwxUSE_LIBJPEG=builtin -DwxUSE_WEBVIEW=ON -DwxUSE_REGEX=builtin -DwxUSE_GLCANVAS_EGL=OFF=OFF

Thanks for the hint. Using `-DwxUSE_GLCANVAS_EGL=OFF` building WxWidgets and rebuilding slade did the trick for me.

**Comment by Blzut3** [comment]
> Might be a case of wxWidgets having different versions and/or code on different distros then?

No.  Since Slade so often finds bugs in wxWidgets it's not viable for my packages to use a system provided copy of wxWidgets while still retaining 5 years of back support for Ubuntu/Debian versions.  The latest version is compiled from the official sources and statically linked.

However like most projects, the build system for wxWidgets auto detects what's available on the system and configures itself so builds can differ.  Or I guess in this case I intentionally disable a feature since it has been noted to be problematic with the current version of wxWidgets.

> Thanks for the hint. Using `-DwxUSE_GLCANVAS_EGL=OFF` building WxWidgets and rebuilding slade did the trick for me.

Oh that's a little surprising.  I was under the impression that others in this thread would have already tried that.  It has been noted that wxWidgets without EGL fixes a TEXTURE editor crash here: https://github.com/sirjuddington/SLADE/issues/1390#issuecomment-1518539182

**Comment by kinker31** [comment]
Although the AUR's pkgbuild has had the `-DwxUSE_GLCANVAS_EGL=OFF` for quite a bit now, I'm still running into the same issue. Both the release and git package crash when I test this. If I had to hazard a guess, I'm not sure the flag that's supposed to be solving the issue is even working, given how this shows up when I build/install the package:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    wxUSE_GLCANVAS_EGL
```

**Comment by Blzut3** [comment]
That needs to be specified on the wxWidgets build not SLADE.  The AUR package maintainer will need to build a custom wxWidgets as part of the SLADE package instead of using the system copy.

**Comment by envolution** [comment]
@kinker31 @Blzut3 can you please try (on arch)
```
$ GDK_BACKEND=x11 slade
```
and see if you can reproduce the error?

If that doesn't resolve it, please try install https://aur.archlinux.org/packages/wxwidgets-gtk3-noegl
and use the same launch command as before

**Comment by kinker31** [comment]
> @kinker31 @Blzut3 can you please try `GDK_BACKEND=x11 slade` and see if you can reproduce the error?
> 
> If that doesn't resolve it, please install https://aur.archlinux.org/packages/wxwidgets-gtk3-noegl and use the same GDK_BACKEND launch command

Although attempting to run Slade directly through the terminal gives me `slade: symbol lookup error: slade: undefined symbol: _ZNK13wxGLCanvasEGL15IsShownOnScreenEv` as a response, I can run the program just fine with the modified wxwidgets package.

![victory](https://github.com/user-attachments/assets/9f11247e-4490-4e73-96dd-845cc130797b)
And I'm proud to finally say it works, at least for now.

**Comment by jmfergeau** [comment]
Well, bad news. I've just installed the patched wxwidgets of @envolution and it resolved nothing for me. Still same problem both for TEXTUREx editor and the start page... So I guess the problem is something else for linux... :(

**Comment by Blzut3** [comment]
@envolution I use Ubuntu and maintain the deb package for Slade, so can't test your package but of course feel free to reach out if you need to compare notes.

For this issue in particular don't worry too much about causing too much packaging noise here since until something changes this is a packaging issue.  As an aside, I think you might be able to set CMAKE_INSTALL_RPATH on the Slade build to avoid needing to run patchelf if you prefer.

@jmfergeau Given you say you have the start page issue definitely double check that you're running under XWayland (GDK_BACKEND=x11).

**Comment by jmfergeau** [comment]
the real problem for me was that I forgot i was using the flatpak version. (for the reason that I could at least reach the editor with this one rather than having an abrupt crash on it.) So I reverted to the aur one. Though I noticed the aur package provides its own wxwidgets it builds with, so I have the feeling the slade built wants to use this one...

anyway @Blzut3 and @envolution I don't use wayland because nvidia so i'm already natively on x11. And still same problem, even if I add GDK_BACKEND=x11.

**Comment by envolution** [comment]
@jmfergeau i made another change to aur/slade that should (hopefully) resolve it for you

**Comment by Blzut3** [comment]
@jmfergeau Wayland should work on nvidia at this point, although I wouldn't blame you for wanting to give it a little more time to bake in their drivers.  Interesting that you're seeing problems on native X11 though, would seem that the problem you're facing may be different from the common one everyone else is facing.  You may want to do a debug build and get a complete stack trace (since the dump you posted in May doesn't have Slade symbol names).

**Comment by jmfergeau** [comment]
@envolution I got the update and tried. Nothing changed, still crashing like before. :/ But well, thanks for trying.

@Blzut3 Wayland works for me but electron-based programs are having problems. And I use several of them (like discord) and can't afford to not use them. Anyway I tried gdb on slade but gdb simply refuses to let me because `"/usr/bin/slade": not in executable format: file format not recognized`... Though if you guys have any tips of things i can do to get you more info, i'd be glad to try.

All i could get is the backtrace given when I try to open a TEXTUREx file on the compiled slade. It doesn't appear on the flatpak version but maybe it's related?

```
ASSERT INFO:
/home/max/.cache/yay/slade/src/wxWidgets/src/unix/glx11.cpp(626): assert ""Assert failure"" failed in InitVisual(): Failed to get a XVisualInfo for the requested attributes.

BACKTRACE:
[1] wxGLCanvasX11::InitVisual(wxGLAttributes const&)
[2] wxGLCanvas::Create(wxWindow*, wxGLAttributes const&, int, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&)
[3] wxGLCanvas::Create(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&, int const*, wxPalette const&)
[4] wxGLCanvas::wxGLCanvas(wxWindow*, int, int const*, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&)
[5] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[6] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[7] wxEvtHandler::TryHereOnly(wxEvent&)
[8] wxEvtHandler::ProcessEventLocally(wxEvent&)
[9] wxEvtHandler::ProcessEvent(wxEvent&)
[10] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[11] g_signal_emit_valist
[12] g_signal_emit
[13] g_signal_emit_valist
[14] g_signal_emit
[15] g_cclosure_marshal_VOID__BOXEDv
[16] g_signal_emit_valist
[17] g_signal_emit
[18] gtk_event_controller_handle_event
[19] g_closure_invoke
[20] g_signal_emit_valist
[21] g_signal_emit
[22] gtk_main_do_event
[23] g_main_loop_run
[24] gtk_main
[25] wxGUIEventLoop::DoRun()
[26] wxEventLoopBase::Run()
[27] wxAppConsoleBase::MainLoop()
[28] wxEntry(int&, wchar_t**)
[29] main
[30] __libc_start_main
```

**Comment by envolution** [comment]
If you're using the aur package, /usr/bin/slade is a shell script, /usr/bin/slade3.bin is the binary you'd want to open with gdb

**Comment by Blzut3** [comment]
Those assertions indicate that wxWidgets is failing to create an OpenGL context for some reason.  (I assume other OpenGL software works fine.)  Search results for that message don't reveal much except that maybe the [attributes](https://github.com/sirjuddington/SLADE/blob/bf00e9f8ffc35d48c1b3d8dd85d7a37731ebd235/src/OpenGL/OpenGL.cpp#L53) specified are incompatible?  Don't know much about OpenGL programming so I really don't know what to make of any of that myself.

**Comment by envolution** [comment]
@jmfergeau  I just want to rule out a possibility of you using older packages I created.  Can you confirm you have the system wxwidgets and slade is linked properly to the custom one (as below)?
```
$ pacman -Q | grep -i wxwidgets-gtk
wxwidgets-gtk3 3.2.6-1

$ ldd /usr/bin/slade3.bin | grep -i gtk3
        libwx_gtk3u_aui-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_aui-3.2.so.0 (0x00007b4b0c55b000)
        libwx_gtk3u_gl-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_gl-3.2.so.0 (0x00007b4b0d57c000)
        libwx_gtk3u_stc-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_stc-3.2.so.0 (0x00007b4b0c200000)
        libwx_gtk3u_propgrid-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_propgrid-3.2.so.0 (0x00007b4b0c450000)
        libwx_gtk3u_webview-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_webview-3.2.so.0 (0x00007b4b0d54d000)
        libwx_gtk3u_core-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_core-3.2.so.0 (0x00007b4b0b800000)
```

**Comment by jmfergeau** [comment]
@envolution here's what I got with the commands you sent:

```
pacman -Q | grep -i wxwidgets-gtk
wxwidgets-gtk3-noegl 3.2.6-1

ldd /usr/bin/slade3.bin | grep -i gtk3
        libwx_gtk3u_aui-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_aui-3.2.so.0 (0x0000722d8f75b000)
        libwx_gtk3u_gl-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_gl-3.2.so.0 (0x0000722d9078e000)
        libwx_gtk3u_stc-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_stc-3.2.so.0 (0x0000722d8f400000)
        libwx_gtk3u_propgrid-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_propgrid-3.2.so.0 (0x0000722d8f650000)
        libwx_gtk3u_webview-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_webview-3.2.so.0 (0x0000722d9075f000)
        libwx_gtk3u_core-3.2.so.0 => /usr/share/slade3/lib/libwx_gtk3u_core-3.2.so.0 (0x0000722d8ea00000)

```

Also, thanks for the point out. I could run gdb on slade and I got the following In this file [slade_gdb_log.txt](https://github.com/user-attachments/files/18336681/slade_gdb_log.txt) I don't know if it can help but just in case...

and yes @Blzut3 I have other stuff using opengl and they all run like a charm. Slade is the only one that doesn't. (And as I'm trying, I just noticed that even the map editor crashes on me. Which is very problematic to me since UDB is very bad on linux and I have no better alternatives for making maps now :( )

**Comment by envolution** [comment]
@jmfergeau you'll definitely want to replace wxwidgets-gtk3-noegl with wxwidgets-gtk3 - it was an unsuccessful attempt at working around the issue.  It's no longer needed as you may notice aur/slade builds wxwidgets-gtk3 internally.  I don't think this is causing the current issue for you, but it's not helping either.

**Comment by jmfergeau** [comment]
@envolution well indeed since same problem with and without so I guess i can revert to the usual one at this point.

**Comment by jmfergeau** [comment]
I found a temporary "fix" to use slade while waiting for the fix: make a vmware machine (because qemu and virtualbox failed there) then install debian then slade via the drd repo. Worked like a charm after some tweaks.

**Comment by jmfergeau** [comment]
I found another issue that seems related to it: the "convert to png" is completely messed up if used on a pc that has the issues. On my tests, the texture ended up being grayscale and all messed up. Though, everything goes fine if I do it on my debian vm.

**Comment by Blzut3** [comment]
@sirjuddington Figured out something.  If I apply this hack, TEXTURE1 in doom1.wad can open successfully without crashing on X11 with EGL enabled.
```diff
diff --git a/src/MainEditor/UI/TextureXEditor/PatchTablePanel.cpp b/src/MainEditor/UI/TextureXEditor/PatchTablePanel.cpp
index 487bcefe..4dcd2958 100644
--- a/src/MainEditor/UI/TextureXEditor/PatchTablePanel.cpp
+++ b/src/MainEditor/UI/TextureXEditor/PatchTablePanel.cpp
@@ -203,6 +203,7 @@ PatchTablePanel::PatchTablePanel(wxWindow* parent, PatchTable* patch_table, Text
        patch_table_{ patch_table },
        parent_{ tx_editor }
 {
+       ((wxNotebook*)parent)->AddPage(this, wxS("Patch Table (PNAMES)"));
        setupLayout();
 
        // Bind events
diff --git a/src/MainEditor/UI/TextureXEditor/TextureXEditor.cpp b/src/MainEditor/UI/TextureXEditor/TextureXEditor.cpp
index 67a44c76..635975e7 100644
--- a/src/MainEditor/UI/TextureXEditor/TextureXEditor.cpp
+++ b/src/MainEditor/UI/TextureXEditor/TextureXEditor.cpp
@@ -456,6 +456,10 @@ bool TextureXEditor::openEntry(ArchiveEntry* tx_entry)
        if (type == "texturex")
        {
                auto tx_panel = new TextureXPanel(tabs_, *this);
+               if (pnames_tab_index_ < 0)
+                       tabs_->AddPage(tx_panel, wxString::FromUTF8(tx_entry->name()));
+               else
+                       tabs_->InsertPage(pnames_tab_index_, tx_panel, wxString::FromUTF8(tx_entry->name()));
 
                // Init texture panel
                tx_panel->Show(false);
@@ -471,10 +475,12 @@ bool TextureXEditor::openEntry(ArchiveEntry* tx_entry)
                        // Add it to the list of editors, and a tab
                        tx_panel->SetName(wxS("textures"));
                        texture_editors_.push_back(tx_panel);
+#if 0
                        if (pnames_tab_index_ < 0)
                                tabs_->AddPage(tx_panel, wxString::FromUTF8(tx_entry->name()));
                        else
                                tabs_->InsertPage(pnames_tab_index_, tx_panel, wxString::FromUTF8(tx_entry->name()));
+#endif
                }
 
                tx_panel->Show(true);
@@ -512,7 +518,7 @@ bool TextureXEditor::openEntry(ArchiveEntry* tx_entry)
        if (pnames_loaded)
        {
                auto ptp = new PatchTablePanel(tabs_, &patch_table_, this);
-               tabs_->AddPage(ptp, wxS("Patch Table (PNAMES)"));
+               //tabs_->AddPage(ptp, wxS("Patch Table (PNAMES)"));
                ptp->SetName(wxS("pnames"));
                pnames_tab_index_ = tabs_->GetPageCount() - 1;
        }
```
Essentially it seems that calling TextureXPanel::openTEXTUREX before adding the panel to the wxNotebook causes the crash.  I suspect the tx_panel->Show lines before and after were put there to avoid a similar issue elsewhere, but they may simply be papering over the code being wrong.

PatchTablePanel is in a worse state since its constructor calls setupLayout which seems to be non-idiomatic?  Whatever the case may be with the gross hack in place to add the tab earlier the pnames tab works fine, but without it Slade will crash when switching tabs from the texture1 editor.

Ultimately what it seems the problem comes down to is performing operations that may trigger layout changes before the widget is properly added.

**Comment by sirjuddington** [comment]
Oh that's interesting, I wonder why that happens, I'm sure there are other places in SLADE where a GL canvas is created for a window that isn't yet shown in a tab...

When you have time can you check if #1863 fixes it?

Either way this just confirms even more that the texture editor needs an overhaul sooner rather than later, it's a bit of a mess both in its UI and the code behind it

**Comment by Blzut3** [comment]
Yep, that seems to do the trick for me.

@jmfergeau While it seems like you might be having a different issue than I was able to reproduce are you able to see if that change also improves things for you?

**Comment by jmfergeau** [comment]
3.2.8 still has the problem.

**Comment by Blzut3** [comment]
Based on comment in the AUR, it seems at least two users have confirmed the texture editor crash is fixed.  Given that I believe this issue history is polluted with two separate issues.

1. The OP's issue which, as far as I can tell, seems to be some initialization problem with Slade and the Nvidia drivers.  Usually software has the opposite problem if not being able to find someone with non-Nvidia hardware and requisite skills to debug, so that's interesting.
2. The issue that I found the fix for which seems to have affected everyone.

Given that the post history of this ticket was unknowingly conflating two issues, and admittedly at the risk of finding out we're still combining more technically unrelated issue, I'm going to suggest we close this issue in favor of #1884?

**Comment by sirjuddington** [comment]
Hmm yeah I think this issue / comment thread has probably grown to encompass a few too many different things, though I'm not 100% convinced #1884 is the exact same issue as this.

I'd be interested to see how things are on 3.3.0, as that is requesting a core opengl context instead of compatibility, and has more robust opengl context creation logic...

**Comment by jmfergeau** [comment]
So far I still have the same issue.

The graphics itself are still not shown. With and without `GDK_BACKEND=x11`.

![As you can see...](https://github.com/user-attachments/assets/dacbdaf6-887f-400b-9f93-7397bd07bef4)

And I have this error both on TEXTUREx viewer and sprites viewer:

```
ASSERT INFO:
/usr/src/debug/wxwidgets/wxWidgets/src/unix/glegl.cpp(388): assert ""Assert failure"" failed in InitVisual(): Failed to get an EGLConfig for the requested attributes.

BACKTRACE:
[1] wxGLCanvasEGL::InitVisual(wxGLAttributes const&)
[2] wxGLCanvas::Create(wxWindow*, wxGLAttributes const&, int, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&)
[3] wxGLCanvas::Create(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&, int const*, wxPalette const&)
[4] wxGLCanvas::wxGLCanvas(wxWindow*, int, int const*, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&)
[5] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[6] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[7] wxEvtHandler::TryHereOnly(wxEvent&)
[8] wxEvtHandler::ProcessEventLocally(wxEvent&)
[9] wxEvtHandler::ProcessEvent(wxEvent&)
[10] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[11] g_signal_emit_valist
[12] g_signal_emit
[13] g_signal_emit_valist
[14] g_signal_emit
[15] g_cclosure_marshal_VOID__BOXEDv
[16] g_signal_emit_valist
[17] g_signal_emit
[18] gtk_event_controller_handle_event
[19] g_closure_invoke
[20] g_signal_emit_valist
[21] g_signal_emit
[22] gtk_main_do_event
[23] g_main_loop_run
[24] gtk_main
[25] wxGUIEventLoop::DoRun()
[26] wxEventLoopBase::Run()
[27] wxAppConsoleBase::MainLoop()
[28] wxEntry(int&, wchar_t**)
[29] main
[30] __libc_start_main
```

I'm sorry to be a bother but there's no other alternatives to SLADE...

**Comment by sirjuddington** [comment]
Can you try changing the `gl_depth_buffer_size` to different values? `0`,`8`,`16`,`24`,`32` (note that ideally you don't want `0` as that disables the depth buffer completely, but just try it to test)

You'll need to restart SLADE each time you change it

**Comment by jmfergeau** [comment]
Thank you for the suggestion.

By default I had it at 64. Changing the value to anything instantly brings the exact same error as above, even with no file loaded. As well as when I set it up to 32 or even bigger values than 64. (I have an 8Gb VRAM Nvidia card)

When I set it to 24 and under, the behavior is different, though. The window that should show the graphics shows pitch black instead of nothing, and the error is different:

```
ASSERT INFO:
/usr/src/debug/wxwidgets/wxWidgets/src/unix/glegl.cpp(616): assert ""Assert failure"" failed in CreateSurface(): Unable to create EGL surface

BACKTRACE:
[1] wxGLCanvasEGL::CreateSurface()
[2] wxGLCanvas::GTKHandleRealized()
[3] wxWindow::PostCreation()
[4] wxWindow::Create(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&)
[5] wxGLCanvas::Create(wxWindow*, wxGLAttributes const&, int, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&)
[6] wxGLCanvas::Create(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&, int const*, wxPalette const&)
[7] wxGLCanvas::wxGLCanvas(wxWindow*, int, int const*, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&)
[8] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[9] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[10] wxEvtHandler::TryHereOnly(wxEvent&)
[11] wxEvtHandler::ProcessEventLocally(wxEvent&)
[12] wxEvtHandler::ProcessEvent(wxEvent&)
[13] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[14] g_signal_emit_valist
[15] g_signal_emit
[16] g_signal_emit_valist
[17] g_signal_emit
[18] g_cclosure_marshal_VOID__BOXEDv
[19] g_signal_emit_valist
[20] g_signal_emit
[21] gtk_event_controller_handle_event
[22] g_closure_invoke
[23] g_signal_emit_valist
[24] g_signal_emit
[25] gtk_main_do_event
[26] g_main_loop_run
[27] gtk_main
[28] wxGUIEventLoop::DoRun()
[29] wxEventLoopBase::Run()
[30] wxAppConsoleBase::MainLoop()
[31] wxEntry(int&, wchar_t**)
[32] main
[33] __libc_start_main
```

Note that it happens with a fresh recompiled from AUR, just to be sure it's not using the old wxwidgets.

**Comment by sirjuddington** [comment]
Hmm ok, I think `32` should be valid for depth buffer size but nothing above that (it's not really 'size' but 'bits'). So it looks like you need to set that to `24`, and yeah now there's another issue.

Do you know what version your nvidia driver is?

**Comment by jmfergeau** [comment]
Using official non-free drivers v580.95.05. Though it's going to be more than a year I have this issue and I don't remember which version I had when it started occurring.

**Comment by jmfergeau** [comment]
Also tried with nvidia opensource drivers on 3.2.9 but problem still occurs (at least on flatpak). No errors display, though.

(And I'm still thinking that it's the same problem as for just displaying textures or the graphical part of the map editor, since the pitch-black or empty render occurs too.)

**Comment by sirjuddington** [comment]
See #1930
